import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/Providers/authProvider/NextAuthSessionProvider";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { icons } from "lucide-react";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// layout.tsx or layout.js

export const metadata = {
  title: "Tour Management System",
  description: "Generated by Tour Management System",
  icons: {
    icon: "https://i.ibb.co.com/TMrScv8t/Screenshot-2025-09-27-074922.png",      // default favicon
    shortcut: "https://i.ibb.co.com/TMrScv8t/Screenshot-2025-09-27-074922.png", // browser shortcut
    apple: "https://i.ibb.co.com/TMrScv8t/Screenshot-2025-09-27-074922.png",    // Apple touch icon
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
       
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </body>
      </NextAuthSessionProvider>
    </html>
  );
}
