// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/Providers/authProvider/NextAuthSessionProvider";
import NavbarFooterWrapper from "@/Providers/authProvider/NavbarFooterWrapper";
// ⚠ Cannot use client hooks here directly

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tour Management System",
  description: "Generated by Tour Management System",
  icons: {
    icon: "https://i.ibb.co.com/TMrScv8t/Screenshot-2025-09-27-074922.png",
    shortcut: "https://i.ibb.co.com/TMrScv8t/Screenshot-2025-09-27-074922.png",
    apple: "https://i.ibb.co.com/TMrScv8t/Screenshot-2025-09-27-074922.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Wrap Navbar/Footer in a client component */}
          <NavbarFooterWrapper>{children}</NavbarFooterWrapper>
        </body>
      </NextAuthSessionProvider>
    </html>
  );
}
